### ISSUE TITLE
Support on 2021.1?

### ISSUE THREAD

**Issue by raymondlo84** [trexdog/openvino-jupyternotebook-tutorials#1]
I was trying to execute tutorial_classification_sample.ipynb on OpenVINO 2021.1 and I got this error. 

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-4-99f268be6277> in <module>
      1 # load network from IR files
----> 2 net = ie.read_network(model=model_xml, weights=model_bin)
      3 print("Loaded model IR files [",model_bin,"] and [", model_xml, "]\n")
      4 
      5 # check to make sure that the plugin has support for all layers in the loaded model

ie_api.pyx in openvino.inference_engine.ie_api.IECore.read_network()

ie_api.pyx in openvino.inference_engine.ie_api.IECore.read_network()

RuntimeError: The support of IR v3 has been removed from the product. Please, convert the original model using the Model Optimizer which comes with this version of the OpenVINO to generate supported IR version.

**Comment by trexdog** [comment]
Hi,
   The message contains the exact error "The support of IR v3 has been removed from the product."  indicating that the model's  .xml and .bin files are IR v3 which is no longer supported in OpenVINO 2021.x.  I have just updated the model files so all the tutorials are consistent and now have IR v10 model files.

Please note that this repository is not officially supported and presently there are no plans to update past OpenVINO 2020.4 nor test on OpenVINO 20201.x.  I have made the update out of courtesy because it was quick and easy enough to do, hopefully it will let you get past the error.
